---
driver:
  name: docker

platforms:
  - name: zabbix-javagateway-${MY_MOLECULE_CONTAINER:-centos}
    image: ${MY_MOLECULE_IMAGE:-"geerlingguy/docker-centos8-ansible"}
    command: ${MY_MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    pre_build_image: true
    networks:
      - name: zabbix
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - ${MY_MOLECULE_INTERPRETER:-python3}
      - ${MY_MOLECULE_VERSION:-v62}

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  env:
    ANSIBLE_COLLECTIONS_PATHS: $HOME/.ansible/collections/ansible_collections/community/zabbix
    ANSIBLE_ROLES_PATH: $HOME/.ansible/collections/ansible_collections/community/zabbix/roles
  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: /usr/bin/python3
      python:
        ansible_python_interpreter: /usr/bin/python
      v62:
        zabbix_javagateway_version: 6.2
      v60:
        zabbix_javagateway_version: 6.0
      v50:
        zabbix_javagateway_version: 5.0

verifier:
  name: testinfra
  lint:
    name: flake8
