---
- name: Setting Web Server Facts
  set_fact:
    zabbix_web_user: "{{ zabbix_web_user if zabbix_web_user is defined else _apache_user }}"
    zabbix_web_group: "{{ zabbix_web_group if zabbix_web_group is defined else _apache_group }}"
    zabbix_web_apache_vhost_location: "{{ zabbix_web_apache_vhost_location if zabbix_web_apache_vhost_location is defined else _apache_vhost_location }}"

- name: "Apache | Get Apache version"
  shell: |
    PATH=/usr/sbin:$PATH
    set -o pipefail
    apachectl -v | grep 'version' | awk -F '/' '{ print $2 }'| awk '{ print $1 }' | cut -c 1-3
  changed_when: false
  register: apachectl_version
  check_mode: false
  args:
    executable: /bin/bash
  tags:
    - zabbix-web

- name: "Apache | Set correct apache_version"
  set_fact:
    apache_version: "{{ apachectl_version.stdout }}"
  tags:
    - zabbix-web

- name: "Apache | Install apache vhost"
  template:
    src: apache_vhost.conf.j2
    dest: "{{ zabbix_web_apache_vhost_location }}"
    owner: "{{ zabbix_web_user }}"
    group: "{{ zabbix_web_group }}"
    mode: 0644
  when: zabbix_vhost
  become: true
  notify:
    - restart apache
  tags:
    - zabbix-server

- name: "Apache | Enable Site (Debian Only)"
  file:
    src: "{{ zabbix_web_apache_vhost_location }}"
    dest: /etc/apache2/sites-enabled/zabbix.conf
    state: link
    owner: root
    group: root
  when: ansible_os_family == "Debian"
