---
- name: "Debian | Include Zabbix gpg ids"
  include_vars: zabbix.yml

- name: "Debian | Set Some Variables"
  set_fact:
    _zabbix_web_apache_php_addition: true

- name: "Debian | Set short version name"
  set_fact:
    zabbix_short_version: "{{ zabbix_version | regex_replace('\\.', '') }}"

- name: "Debian | Install gpg key"
  apt_key:
    id: "{{ sign_keys[zabbix_short_version][ansible_distribution_release]['sign_key'] }}"
    url: http://repo.zabbix.com/zabbix-official-repo.key
  when:
    - zabbix_repo == "zabbix"
  become: true
  tags:
    - zabbix-web
    - init
    - config

- name: "Debian | Installing repository {{ ansible_distribution }}"
  apt_repository:
    repo: "{{ item }} http://repo.zabbix.com/zabbix/{{ zabbix_version }}/{{ ansible_distribution.lower() }}/ {{ ansible_distribution_release }} main"
    state: present
  become: true
  when:
    - zabbix_repo == "zabbix"
    - ansible_machine != "aarch64"
  with_items:
    - deb-src
    - deb
  tags:
    - zabbix-web
    - init
    - config

- name: "Debian | Installing repository {{ ansible_distribution }}"
  apt_repository:
    repo: "{{ item }} http://repo.zabbix.com/zabbix/{{ zabbix_version }}/{{ ansible_distribution.lower() }}-arm64/ {{ ansible_distribution_release }} main"
    state: present
  become: true
  when:
    - zabbix_repo == "zabbix"
    - ansible_machine == "aarch64"
  with_items:
    - deb-src
    - deb
  tags:
    - zabbix-web
    - init
    - config

- name: "Debian | Install zabbix-web"
  apt:
    pkg: "zabbix-frontend-php{{ '-deprecated' if zabbix_php_frontend_deprecated else '' }}"
    state: "{{ zabbix_web_package_state }}"
    update_cache: true
    cache_valid_time: 0
  environment:
    http_proxy: "{{ zabbix_http_proxy | default(None) | default(omit) }}"
    https_proxy: "{{ zabbix_https_proxy | default(None) | default(omit) }}"
  register: zabbix_web_package_install
  until: zabbix_web_package_install is succeeded
  become: true
  tags:
    - zabbix-web
    - init
    - config

- name: "Debian | Link graphfont.ttf (workaround ZBX-10467)"
  file:
    src: "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
    path: "/usr/share/zabbix/fonts/graphfont.ttf"
    state: link
  tags:
    - zabbix-web
    - init
    - config

- name: "Debian | Install PHP"
  template:
    src: php-fpm.conf.j2
    dest: "{{ zabbix_php_fpm_dir }}/zabbix.conf"
    owner: "{{ _apache_user }}"
    group: "{{ _apache_group }}"
    mode: 0644
  become: true
  when:
    - zabbix_vhost
  notify:
    - restart php-fpm-version

- name: "Including Apache Configuration"
  include_tasks: apache_Debian.yml
  vars:
    zabbix_web_server_name: "{{ zabbix_web_server_name }}"
  when:
    - zabbix_web_http_server == 'apache'
