---
_apache_user: apache
_apache_group: apache
_apache_log: httpd
_apache_service: httpd
_apache_vhost_location: /etc/httpd/conf.d/zabbix.conf

_php_fpm_dir: /etc/php-fpm.d
_php_fpm_session: /var/lib/php/session
_zabbix_php_fpm_listen: /run/php-fpm/zabbix.sock

_nginx_user: nginx
_nginx_group: nginx
_nginx_config_path: /etc/nginx/conf.d
_nginx_log_path: /var/log/nginx
_nginx_service: nginx
# _nginx_tls_crt: /etc/pki/server.crt
# _nginx_tls_key: /etc/pki/server.key
# _nginx_tls_dhparam: /etc/pki/dhparam-server.pem

zabbix_valid_web_versions:
  "9":
    - 6.2
    - 6.0
  "8":
    - 6.2
    - 6.0
    - 5.0
  "7":
    - 5.0

# zabbix_web_php_dependencies:
#   - "php{{ zabbix_web_php_installed_version }}-php-gd"
#   - "php{{ zabbix_web_php_installed_version }}-php-bcmath"
#   - "php{{ zabbix_web_php_installed_version }}-php-xml"
#   - "php{{ zabbix_web_php_installed_version }}-php-mbstring"
#   - "php{{ zabbix_web_php_installed_version }}-php-ldap"
#   - "php{{ zabbix_web_php_installed_version }}-php-{{ 'pgsql' if zabbix_server_database == 'pgsql' else 'mysqlnd' }}"

zabbix_web_php_dependencies:
  - "php-gd"
  - "php-bcmath"
  - "php-xml"
  - "php-mbstring"
  - "php-ldap"
  - "php-{{ 'pgsql' if zabbix_server_database == 'pgsql' else 'mysqlnd' }}"

zabbix_selinux_dependencies:
  "9":
    - python3-libsemanage
  "8":
    - python3-libsemanage
  "7":
    - libsemanage-python
